/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.OperaterWorkarea;

import com.neu5100.finalproject.data.Test;
import com.neu5100.finalproject.model.IncidentOps;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.SuicideWorkarea.SuicideWorkareaJPanel;
import userinterface.disasterWorkarea.DisasterWorkareaJPanel;

/**
 *
 * @author chenghongmei
 */
public class OperaterWorkareaJPanel extends javax.swing.JPanel {

     private JPanel OperatorProcessContainer;
     private IncidentOps ops;
    /**
     * Creates new form OperaterWorkareaJPanel
     */
    public OperaterWorkareaJPanel(JPanel user ,IncidentOps incidentOps ) {
        initComponents();
        this.OperatorProcessContainer = user;
        this.ops = incidentOps;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnDisaster = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnProcess1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        EventTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnSuiside = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("911 OPERATOR WORK AREA");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnDisaster.setText("report to disaster organization");
        btnDisaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisasterActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnProcess1.setText("Process");
        btnProcess1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcess1ActionPerformed(evt);
            }
        });

        EventTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "emergency ID", "Police", "Hospital", "firesaty", "status"
            }
        ));
        jScrollPane2.setViewportView(EventTable1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel Request");

        btnSuiside.setText("report to suicide organization");
        btnSuiside.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuisideActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(251, 251, 251)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(55, 55, 55)
                                    .addComponent(btnProcess1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50)
                                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnDisaster)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSuiside, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnProcess1)
                    .addComponent(btnView))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisaster)
                    .addComponent(btnSuiside))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
       CreateJPanel createJPanel  = new  CreateJPanel (OperatorProcessContainer,ops);
       OperatorProcessContainer.add("CreatJPanel",createJPanel);
       CardLayout layout = (CardLayout)OperatorProcessContainer.getLayout();
       layout.next(OperatorProcessContainer);
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnProcess1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcess1ActionPerformed
        // TODO add your handling code here:
        
       int selectedRowIndex = EventTable1.getSelectedRow();
       if ( selectedRowIndex < 0){
           JOptionPane.showMessageDialog(this, "Please select an order first.");
            return;
       }       
        
       DefaultTableModel model = (DefaultTableModel) EventTable1.getModel();  
        
        
     ProcessJPanel processJPanel = new ProcessJPanel(OperatorProcessContainer,(int)model.getValueAt(selectedRowIndex, 0));
     OperatorProcessContainer.add("ProcessJPanel",processJPanel);
     CardLayout layout = (CardLayout)OperatorProcessContainer.getLayout();
     layout.next(OperatorProcessContainer);
           
        
    }//GEN-LAST:event_btnProcess1ActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
    int selectedRowIndex = EventTable1.getSelectedRow();
    if ( selectedRowIndex < 0){
        JOptionPane.showMessageDialog(this, "Please select an order first.");
        return;
    }       
        
       DefaultTableModel model = (DefaultTableModel) EventTable1.getModel();
        
        ViewEventJPanel viewEventJPanel = new ViewEventJPanel(OperatorProcessContainer, (int)model.getValueAt(selectedRowIndex, 0));
        OperatorProcessContainer.add("ViewEventJPanel",viewEventJPanel);
        CardLayout layout = (CardLayout)OperatorProcessContainer.getLayout();
        layout.next(OperatorProcessContainer);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDisasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisasterActionPerformed
        // TODO add your handling code here:
            int selectedRowIndex = EventTable1.getSelectedRow();
    if ( selectedRowIndex < 0){
        JOptionPane.showMessageDialog(this, "Please select an order first.");
        return;
    }       
        
       DefaultTableModel model = (DefaultTableModel) EventTable1.getModel();
        
        DisasterWorkareaJPanel disasterWorkareaJPanel = new DisasterWorkareaJPanel(OperatorProcessContainer, (int)model.getValueAt(selectedRowIndex, 0));
        OperatorProcessContainer.add("DisasterWorkareaJPanel",disasterWorkareaJPanel);
        CardLayout layout = (CardLayout)OperatorProcessContainer.getLayout();
        layout.next(OperatorProcessContainer);
        
        
    }//GEN-LAST:event_btnDisasterActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSuisideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuisideActionPerformed
        // TODO add your handling code here:
    int selectedRowIndex = EventTable1.getSelectedRow();
    if ( selectedRowIndex < 0){
        JOptionPane.showMessageDialog(this, "Please select an order first.");
        return;
    }       
        
       DefaultTableModel model = (DefaultTableModel) EventTable1.getModel();
        
        SuicideWorkareaJPanel suicideWorkareaJPanel = new SuicideWorkareaJPanel(OperatorProcessContainer, (int)model.getValueAt(selectedRowIndex, 0));
        OperatorProcessContainer.add("SuicideWorkareaJPanel",suicideWorkareaJPanel);
        CardLayout layout = (CardLayout)OperatorProcessContainer.getLayout();
        layout.next(OperatorProcessContainer);
    }//GEN-LAST:event_btnSuisideActionPerformed

    
     public void populateOrderTable(){
       DefaultTableModel model = (DefaultTableModel) tableOrderList.getModel();
        model.setRowCount(0);
       for (OrderRequest workRequest: customer.getCustomerAccount().getWorkQueue().getOrderRequestList()) {
            Object row[] = new Object[5];
            System.out.println(workRequest);
            row[0] = workRequest;
            row[1] = workRequest.getRestaurant().getRestaurantAccount().getEmployee().getName();
            DeliveryMan deliveryMan = workRequest.getDeliveryMan();
            row[2] = deliveryMan == null ? "Waiting for choice" : deliveryMan.getDeliveryManAccount().getEmployee().getName();
            row[3] = workRequest.getStatus();
           row[4] = workRequest.getComment();
            model.addRow(row);
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EventTable1;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDisaster;
    private javax.swing.JButton btnProcess1;
    private javax.swing.JButton btnSuiside;
    private javax.swing.JButton btnView;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private static class tableOrderList {

        public tableOrderList() {
        }
    }
}
