/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.disasterWorkarea;

import com.neu5100.finalproject.model.AssignWorkRequest;
import com.neu5100.finalproject.model.Disaster;
import com.neu5100.finalproject.model.IncidentOps;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liuyi
 */
public class DisasterWorkareaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private IncidentOps ops;
   
    /**
     * Creates new form disasterOpreatorWorkarea
     */
    public DisasterWorkareaJPanel(JPanel userProcessContainer, IncidentOps ops) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ops = ops;
        //id---->ops
        refresh();
        refreshWR();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReject = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisaster = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnManagetoAlert = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblreques = new javax.swing.JTable();

        btnReject.setText("assign to request");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        tblDisaster.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "level", "allowed vol", "max voluntary"
            }
        ));
        jScrollPane1.setViewportView(tblDisaster);

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel2.setText("Manage Disaster Request");

        btnManagetoAlert.setText("Manage to Alert");

        add.setText("add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        tblreques.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "assign_id", "emergency ID", "need_police", "need_hospital", "need_fireman", "status", "disaster_id"
            }
        ));
        jScrollPane3.setViewportView(tblreques);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnManagetoAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReject)
                    .addComponent(btnManagetoAlert)
                    .addComponent(add))
                .addGap(65, 65, 65)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        int row = tblDisaster.getSelectedRow();
        if ( row < 0){
            JOptionPane.showMessageDialog(this, "Please select a row first.");
            return;
        } 
        Disaster d = (Disaster)tblDisaster.getValueAt(row, 0);
        int selectedRowIndex = tblreques.getSelectedRow();
        if ( selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row first.");
            return;
        } 
        AssignWorkRequest awr = (AssignWorkRequest)tblreques.getValueAt(selectedRowIndex, 0);
        awr.setDisaster_id(d.getDisaster_id());
        awr.update();
        JOptionPane.showMessageDialog(this, "disaster assign to request success.");
        refreshWR();
    }//GEN-LAST:event_btnRejectActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        AddDisasterJPanel adjp = new AddDisasterJPanel(userProcessContainer,ops);
        userProcessContainer.add(adjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton btnManagetoAlert;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblDisaster;
    private javax.swing.JTable tblreques;
    // End of variables declaration//GEN-END:variables

    public  void refresh() {
        int rowCount = tblDisaster.getRowCount();
        DefaultTableModel model = (DefaultTableModel) tblDisaster.getModel();
        for(int i=rowCount-1;i>=0;i--){
            model.removeRow(i);
        }
        
        for (Disaster di:ops.queryDisaster()) {
                
               Object row[] = new Object[4];
                row[0] = di;
                row[1] = di.getDisaster_name();
                row[2] = di.getDisaster_level();
                row[3] = di.getMax_voluntary();
                model.addRow(row);
           
            
            
        }
    }
    public void refreshWR() {
        int rowCount = tblreques.getRowCount();
        DefaultTableModel model = (DefaultTableModel) tblreques.getModel();
        for(int i=rowCount-1;i>=0;i--){
            model.removeRow(i);
        }
        
        for (AssignWorkRequest awr:ops.queryWorkRequestByRole()) {
                
               Object row[] = new Object[7];
                row[0] = awr;
                row[1] = awr.getEmergency_id();
                row[2] = awr.getNeed_police();
                row[3] = awr.getNeed_hospital();
                row[4] = awr.getNeed_firman();
                row[5] = awr.getSatus();
                row[6] = awr.getDisaster_id();
                model.addRow(row);

        }
    }
}
