/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Main;

import com.neu5100.finalproject.model.IncidentOps;
import com.neu5100.finalproject.model.OrganizationAdmin;
import com.neu5100.finalproject.ui.FiremanOffice.FiremanWorkArea;
import com.neu5100.finalproject.ui.HospitalOffice.HospitalWorkArea;
import com.neu5100.finalproject.ui.PoliceOffice.PoliceWorkArea;
import com.neu5100.finalproject.ui.VoluntaryOffice.VoluntaryWorkArea;
import java.awt.CardLayout;
import userinterface.OperaterWorkarea.OperaterWorkareaJPanel;
import userinterface.SystemadminWorkarea.SystemadminWorkareaJpanel;
import userinterface.disasterWorkarea.DisasterWorkareaJPanel;
import userinterface.volunteer.register.VolunteerRegisterJpanel;

/**
 *
 * @author chenghongmei
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
       chooseRole.removeAllItems();
        chooseRole.addItem("police");
        chooseRole.addItem("Police admin");
        chooseRole.addItem("fireman");
        chooseRole.addItem("fireman admin");
        chooseRole.addItem("hospital");
        chooseRole.addItem("hosptial admin");
        chooseRole.addItem("911 ops");
        chooseRole.addItem("voluntary admin");
        chooseRole.addItem("voluntary");
        chooseRole.addItem("disaster Operator");
        chooseRole.addItem("Suicide Prevention Operator");
        chooseRole.addItem("System admin");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        pw = new javax.swing.JTextField();
        btnlogin = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chooseRole = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Emergency System");

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        btnlogin.setText("login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        btnlogout.setText("logout");

        btnRegister.setText("register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel2.setText("if you want to be a volunteer, you need to register here.");

        lblUsername.setText("username");

        jLabel3.setText("password");

        chooseRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        chooseRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseRoleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(pw)))
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnRegister))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(chooseRole, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblUsername)
                .addGap(1, 1, 1)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnlogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnlogout)
                .addGap(37, 37, 37)
                .addComponent(chooseRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegister)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        VolunteerRegisterJpanel vr =   new VolunteerRegisterJpanel(jPanel2);
        jPanel2.add(vr);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.next(jPanel2);   
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        String role = (String)chooseRole.getSelectedItem();
        if(role.equals("fireman admin")){
            OrganizationAdmin oa = new OrganizationAdmin(name.getText(), pw.getText(),1);
            if(oa.login()){
                    FiremanWorkArea fwarea =   new FiremanWorkArea(jPanel2, oa);
                    jPanel2.add(fwarea);
                     CardLayout layout = (CardLayout)jPanel2.getLayout();
                    layout.next(jPanel2);                                                           
                return;
            }
        }
        
        if(role.equals("Police admin")){
            OrganizationAdmin oa = new OrganizationAdmin(name.getText(), pw.getText(),0);
            if(oa.login()){
                    PoliceWorkArea pwarea =   new PoliceWorkArea(jPanel2, oa);
                    jPanel2.add(pwarea);
                     CardLayout layout = (CardLayout)jPanel2.getLayout();
                    layout.next(jPanel2);                                                           
                return;
            }
        }
        if(role.equals("911 ops")){
            IncidentOps ops = new IncidentOps(name.getText(),pw.getText(),0);
            if(ops.login()){
                    OperaterWorkareaJPanel owjp = new OperaterWorkareaJPanel(jPanel2,ops);
                    jPanel2.add(owjp);
                     CardLayout layout = (CardLayout)jPanel2.getLayout();
                    layout.next(jPanel2);                                                           
                return;
            }
        }
        if(role.equals("Suicide Prevention Operator")){
            IncidentOps ops = new IncidentOps(name.getText(),pw.getText(),1);
            if(ops.login()){
                    OperaterWorkareaJPanel owjp = new OperaterWorkareaJPanel(jPanel2,ops);
                    jPanel2.add(owjp);
                     CardLayout layout = (CardLayout)jPanel2.getLayout();
                    layout.next(jPanel2);                                                           
                return;
            }
        }
        if(role.equals("hosptial admin")){
             OrganizationAdmin oa = new OrganizationAdmin(name.getText(), pw.getText(),2);
            if(oa.login()){
                    HospitalWorkArea area = new HospitalWorkArea(jPanel2,oa);
                    jPanel2.add(area);
                     CardLayout layout = (CardLayout)jPanel2.getLayout();
                    layout.next(jPanel2);                                                           
                return;
            }
        }
         if(role.equals("voluntary admin")){
             OrganizationAdmin oa = new OrganizationAdmin(name.getText(), pw.getText(),3);
            if(oa.login()){
                   VoluntaryWorkArea area = new VoluntaryWorkArea(jPanel2, oa);
                    jPanel2.add(area);
                     CardLayout layout = (CardLayout)jPanel2.getLayout();
                    layout.next(jPanel2);                                                           
                return;
            }
        }
        if(role.equals("disaster Operator")){
             IncidentOps ops = new IncidentOps(name.getText(), pw.getText(), 2);
            if(ops.login()){
                   DisasterWorkareaJPanel dwjp = new DisasterWorkareaJPanel(jPanel2, ops);
                    jPanel2.add(dwjp);
                     CardLayout layout = (CardLayout)jPanel2.getLayout();
                    layout.next(jPanel2);                                                           
                return;
            }
        }
        if(role.equals("System admin")){
              OrganizationAdmin oa = new OrganizationAdmin(name.getText(), pw.getText(),4);
            if(oa.login()){
                   SystemadminWorkareaJpanel dwjp = new SystemadminWorkareaJpanel(jPanel2, oa);
                    jPanel2.add(dwjp);
                     CardLayout layout = (CardLayout)jPanel2.getLayout();
                    layout.next(jPanel2);                                                           
                return;
            }
        }
        
        System.out.println("login false");
    }//GEN-LAST:event_btnloginActionPerformed

    private void chooseRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseRoleActionPerformed

 
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnlogout;
    private javax.swing.JComboBox<String> chooseRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pw;
    // End of variables declaration//GEN-END:variables
}
